from typing import Any, Dict, List, Optional

def login(username: str, password: str) -> Dict[str, Any]: ...
def get_all_stock_orders() -> List[Dict[str, Any]]: ...
def get_all_option_orders() -> List[Dict[str, Any]]: ...
def get_all_positions() -> List[Dict[str, Any]]: ...
def get_open_stock_positions() -> List[Dict[str, Any]]: ...
def get_open_option_positions() -> List[Dict[str, Any]]: ...
def get_symbol_by_url(instrument_url: str) -> Optional[str]: ...

orders: Any
options: Any
stocks: Any
crypto: Any
