name: Setup Environment
description: Setup Python, uv, and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: astral-sh/setup-uv@v4
      with:
        version: latest
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
    - name: Install dependencies
      run: uv sync --dev
      shell: bash
